### ISSUE TITLE
negative number macro not working

### ISSUE THREAD

**Issue by bakaiadam** [Scylardor/cminify#1]
this was the input
# define MAXIMUM_SCALE   16383
# define ESCAPE          256
# define DONE            -1
# define FLUSH           -2

this was the output:
# define MAXIMUM_SCALE 16383
# define ESCAPE 256
# define DONE-1
# define FLUSH-2
# define BUFFER_SIZE 256

**Comment by Scylardor** [comment]
Hi, thanks for reporting !

This particular issue should be fixed by c412abf.
It shows the limits of making a sort-of-C-parser using regexes as unary operators are treated like binary ones. I fixed this problem for now but there might be others...

Funnily enough GCC gives a warning for an expression like "#define DONE-1", but not for "#define MIN(a)-a", so we're also good on that kind of expression.
