### ISSUE TITLE
overly aggressive whitespace removal

### ISSUE THREAD

**Issue by evandrix** [Scylardor/cminify#2]
from blog article published [here](http://tuxdiary.com/2015/11/25/binary-printf),

minifying the following source code:

```
void printbin(long long val)
{
        int count = 63; 
        char binstr[65] = {0};

        if (!val) {
                printf("0b0");
                return;
        }   

        /* If negative, get the 2's complement */
        if (val < 0) {
                printf("-0b");
                val = ~val + 1;
         } else
                printf("0b");

         while (val && count >= 0) {
                binstr[count--] = "01"[val & 1]; 
                val >>= 1;
        }   

        count++;

        if (val)
                printf("OVERFLOW %s", binstr + count);
        else
                printf("%s", binstr + count);
}
```

produced:

```
void printbin(long long val){int count=63;char binstr[65]={0};if(!val){printf("0b0");return;}if(val<0){printf("-0b");val=~val+1;}elseprintf("0b");while(val && count>=0){binstr[count--]="01"[val & 1];val>>=1;}count++;if(val)printf("OVERFLOW %s",binstr+count);elseprintf("%s",binstr+count);}
```

it's missing a `<SPACE>` between the `else` and `printf`.

**Comment by Scylardor** [comment]
Hi, thanks for reporting!

I hadn't thought of the corner case of the else keyword, that may or may not have to be followed by a space, depending on whether it is followed by an opening brace or not...

A fix is done by 6c98b43, this is a "quick and easy" one although I'm not very fond of this kind of method since it makes us reprocess what should be the final text, which could be pretty huge. This is a problem due to not having a proper parse tree. But that should do the trick in most cases.
